version: "3.8"

services:
  ldapssp:
    build: .
    container_name: ldapssp
    restart: "${SSP_RESTART}"
    environment:
      - APACHE_SERVER_NAME: "${SSP_WEB_HOST}"
    volumes:
      # log files - optional
      - ldapssp-logs:/var/log/apache2
      # configuration file for ldap-ssp
      - "${SSP_CONFIG}:/config"
    ports:
      - "${SSP_WEB_PORT}":80

volumes:
  ldapssp-logs:
    driver: local